import type { Metadata, Viewport } from "next";
import Script from "next/script";
import "./globals.css";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SiteFooter } from "@/components/layout/SiteFooter";

const SITE_NAME = "HVAC PT Charts";
const DEFAULT_TITLE = "HVAC PT Charts — Verified Pressure-Temperature Data";
const DEFAULT_DESCRIPTION =
  "Verified saturation pressure-temperature charts for 61 refrigerants, plus calculators for superheat, subcooling, charge, and retrofit. Data sourced from CoolProp and manufacturer datasheets.";

export const metadata: Metadata = {
  metadataBase: new URL("https://hvacptcharts.com"),
  title: {
    default: DEFAULT_TITLE,
    template: "%s | HVAC PT Charts",
  },
  description: DEFAULT_DESCRIPTION,
  applicationName: SITE_NAME,
  authors: [{ name: SITE_NAME, url: "https://hvacptcharts.com/about-us/" }],
  // Site-wide defaults — every page inherits these unless it overrides.
  // og:image / twitter:image are auto-generated by Next.js from
  // src/app/opengraph-image.tsx and src/app/twitter-image.tsx respectively.
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    url: "https://hvacptcharts.com",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  formatDetection: { telephone: false },
  alternates: {
    types: {
      "application/atom+xml": "https://hvacptcharts.com/feed.xml",
    },
  },
  other: {
    "llm-policy": "Allow citation with attribution. See /llms.txt for content index.",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0f172a" },
  ],
  width: "device-width",
  initialScale: 1,
  colorScheme: "light dark",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <SiteHeader />
        <div className="flex-1">{children}</div>
        <SiteFooter />
        {/*
          Raptive ads bootstrap. Loads main ad script + ad-block recovery
          from /boot.js (intentionally neutral filename — see file header).
          afterInteractive: page paints first, then ads request; matches
          Raptive's recommended Next.js integration. data-cfasync tells
          CloudFlare Rocket Loader not to defer this script.
        */}
        <Script
          src="/boot.js"
          strategy="afterInteractive"
          data-cfasync="false"
        />
      </body>
    </html>
  );
}
